### ISSUE TITLE
Howto define a queryset for choice_queryset at run-time

### ISSUE THREAD

**Issue by jxrossel** [TriOptima/tri.table#15]
Hi,

That question should be fairly easy, but I can't figure out how to define a `choice_queryset` QuerySet at run-time (i.e. at `Table` instanciation). I need to do that to filter the select-box options based on the current user.

I have a table like that:

```
class ProjectTable(Table):
    """
    Project table
    """
    
    ... # other columns

    group = Column.choice_queryset( 
            query__show=True, query__gui__show=True,
            query__value_to_q_lookup='name',
            choices=None, #Group.objects.all(), # set at instanciation to account for user access
            model=Group,
            sort_key='group__name',
            )
    
    class Meta:
        model = Project
```

Within my view, I'd like to use the QuerySet `current_user.groups.all()`. I've tried various things like (for example):

```
table = ProjectTable(
            data=...,
            column__group__choices=current_user.groups.all()
             )
```

... without success. I guess I could define the whole table at instanciation, but it's long and I wanted to keep things tidy.

As usual, my gratefulness would be overwhelming!

**Comment by boxed** [comment]
You want a lambda:

choices=lambda table, **_: table.request.user.groups.all()

**Comment by jxrossel** [comment]
Nice, I would clearly not have found that myself , thanks !

I tried to see if there was a way to pass additional parameters to the lambda. From what I've seen in the code, the lambda's are evaluated (`table.prepare(request)`) before the context is given to the table (`table.context = table_context(...)`), so that one cannot use the context for that. A not-so-elegant-but-working solution is to add some custom attributes to `request`

**Comment by jlubcke** [comment]
A slightly more elegant way than to add it to `request` is to use the `extra` namespace on `Form`:

    class MyForm(Form):
        foo = Field(
            show=lambda form, **_: form.extra.bar == 17
            ...
        )

    my_form = MyForm(extra__bar=17)

**Comment by jxrossel** [comment]
Thanks for the feedback! I guess that needs to be adapted to the Table case, but I get the idea

**Comment by boxed** [comment]
Yea, just reaching into the request object assumes you're never gonna use that table outside of a web context, which might be incorrect. You might want to do some batch export to CSV or whatever and in that case it makes more sense to put the extra data in extra..as it were.

**Comment by boxed** [comment]
Did you get it to work like you wanted?

**Comment by jxrossel** [comment]
Yes, thanks for the advice !

**Comment by boxed** [comment]
That's great to hear!

Maybe we should sort of consider this ticket a lack-of-documentation ticket. There's some hint at what we can do in the README, but clearly it's not close to good enough.

Looking at the API reference part of the docs doesn't help either.... we do have a project of generating better (and interactive!) documentation for what parameters can be sent to Column, Table, Field, Form, et al.. but it's a bit early yet.

**Comment by jxrossel** [comment]
Well, I would be very happy to have something more on the docs side, although digging into the code can also be interesting...

As a side comment, I am currently digging a bit into the admin site for Django and I'm still wondering why the admin site isn't written in a more reusable way. In particular, the `changelist_view` gives you tables (or formsets) with pagination, filtering, ordering, bulk actions and more for free but you cannot readily embed it in the "front-end" site...

**Comment by boxed** [comment]
Regarding the admin side:  🙄 yea.. it's really silly in my opinion how much time they've spent on it that everyone has to duplicate. I started making an admin site based on tri.table a while back, but just haven't had any time/energy to work on it: https://github.com/boxed/great_apis/blob/master/foo/foo/views.py#L181

It's pretty cool I think. It's a level of abstraction on top of tri.table and tri.form with the same kind of dispatch stuff down to the underlying views. Fully reusable and fully configurable, which nice defaults you an override and everything. Just needs some polishing (it uses some old ideoms from tri.declarative for example)... 89 lines of code for an autogenerated admin is pretty cool I think :P

**Comment by jxrossel** [comment]
You should send the Django guys a link, maybe they'll do the polishing for you ;-)

**Comment by boxed** [comment]
Just FYI there's an admin in iommi, which is the package that follows tri.table.
