### ISSUE TITLE
Filter on boolean field

### ISSUE THREAD

**Issue by jxrossel** [TriOptima/tri.table#17]
Hi,

If I use:
```
myfield = Column.boolean( 
            query__gui__show=True,
            )
```
to filter a table on a boolean field, the state of the filter is always either True or False after the 1st use, i.e. it cannot be reset to "undefined" (so that all records are displayed, without filtering on `myfield`).

I tried to use `Column.choice` instead, but the choice argument expects a list of strings, which will never match a True or False value...

I'd be most thankful for any input here!

**Comment by jlubcke** [comment]
We have fixed this with a custom column (and variable and field) type in our own codebase, but it should probably be moved into tri.[form|query|table]. 

For the impatient it looks roughly like this:
 
```
from tri.form import Field, Shortcut, choice_parse
from tri.query import Variable, boolean_value_to_q
from tri.table import Column

boolean_tristate_field = Shortcut(
    choices=[True, False],
    parse=choice_parse,
    choice_to_option=lambda form, field, choice, **_: (
        choice,
        'true' if choice else 'false',
        'Yes' if choice else 'No',
        choice == field.value,
    ),
    required=False,
    call_target=Field.choice,
)

boolean_tristate_variable = Shortcut(
    gui__call_target=boolean_tristate_field,
    value_to_q=boolean_value_to_q,
    call_target=Variable,
)

boolean_tristate_column = Shortcut(
    query__call_target=boolean_tristate_variable,
    call_target=Column.boolean,
)
```

  / Johan

**Comment by jxrossel** [comment]
Hi,

Thanks for the answer. I tried this code, but `choice_parse` is not implemented in `tri.form`. Anyway, that would be a nice feature to have.

**Comment by boxed** [comment]
Column.boolean_tristate is now implemented in tri.table directly. I think this should solve this. If not, please reopen it.
