### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by ulmus** [TriOptima/tri.table#28]
We use Bootstrap 4 for internal sites, where tri.table would be a great addition. Currently, I override the templates, but it's mostly a question of setting the correct classes to the tags. Tables are easy and redefinable, but things such as pagination requires template overrides. Overriding templates is a bit of a maintenance nightmare.

* Suggestion one: Support "rendering styles" and make bootstrap 4 an option out of the box. Increases maintenance workload, but makes it work ootb with more installations (specifically internal) and could be extended to other frameworks (at the cost of more maintenance). I could do a PR with this.
* Suggestion two: Support more redefined attrs for paginator et al (wouldn't help in this case, the whole markup needs to be updated to support BS4)
* Suggestion three: Support a "rendering plugin system" where I could make a tri.table.bs4 package that changes the rendering. This could be done today with just overriding some templates, but requires template loaders and installed_apps to be correctly set.
* Suggestion four: Close this and maybe improve documentation on overriding the templates with BS4 as an example

Thoughts?

**Comment by boxed** [comment]
Overriding paginator template isn't that bad is it? 

```python
import tri_table

class Table(tri_table.Table):
    class Meta:
        paginator__template = 'my_paginator.html'
```

Then always use this Table in your code. You should do that anyway because you're gonna want to have a central place for global config and adding custom shortcuts.

Actually you should also do the same with the Column, Form, Field, Query and Variable classes and plug that in like:

```python
class Table(tri_table.Table):
    class Meta:
        member_class = Column
        form_class = Form
        query_class = Query
```

etc. 

We should really have a good section on how to properly integrate tri.table/query/form into a product, so this ticket could be a good start to produce that document!

**Comment by boxed** [comment]
Actually, how about you buy us coffee and we'll come over a while and give you some on premise support? :P

**Comment by ulmus** [comment]
How about that :) Went with old school template for the table for now, but really would like to try out the tri.table. I'll DM you about that coffee :)

**Comment by boxed** [comment]
A related question: do you use standard bootstrap or bootstrap react? 

It seems there are no good ajaxy selects outside of a proper front end so I'm leaning towards targeting bootstrap react by default to be able to get react-select by default too.

**Comment by boxed** [comment]
This is fixed in [iommi](http://iommi.rocks)

Bootstrap is the default now, but you can also support other design systems, with Semantic UI support also shipping in iommi.
