### ISSUE TITLE
`render_table` crashes when `table` is passed as positional argument

### ISSUE THREAD

**Issue by simonpercivall** [TriOptima/tri.table#9]

**Comment by boxed** [comment]
Yea, it's in the changelog: https://github.com/TriOptima/tri.table/blob/master/HISTORY.rst

**Comment by simonpercivall** [comment]
Ah, I see. Since it's … a bit weird having required parameters being keyword-only (I don't want to use the word unpythonic, but it's a struggle), I'd suggest the docstring mentioning it.

**Comment by boxed** [comment]
Unpython2ic sure. But not unpython3ic considering the addition of "def foo(*,". 

The docstring should be updated though I agree.

**Comment by boxed** [comment]
This is fixed in [iommi](http://iommi.rocks) (as we don't support python 2 anymore and are explicit with keyword only arguments)
